services:
  postgres:
    image: postgres:16-alpine
    container_name: marble-and-arch-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marble-and-arch
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - marble-and-arch-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: marble-and-arch-api
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/marble-and-arch
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - JWT_SECRET=3cfa76ef14937c1c0ea519f8fc57452c062e00b9ac1507759d5b94bb31375d8f
    depends_on:
      - postgres
    networks:
      - marble-and-arch-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: marble-and-arch-frontend
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_BASE=http://backend:8081/api
    depends_on:
      - backend
    networks:
      - marble-and-arch-network

networks:
  marble-and-arch-network:
    driver: bridge

volumes:
  postgres_data:
