services:
  postgres:
    image: postgres:16-alpine
    container_name: marble-and-arch-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marble-and-arch
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
