spring.application.name=property-management
api.version=v1
server.port=8081
spring.profiles.active=dev
api.security.token.secret=${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc57452c062e00b9ac1507759d5b94bb31375d8f}

# Database Migration with Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Spring Modulith Configuration
# We let Flyway create/manage the table, so we set schema-action to none or validate
spring.modulith.events.jdbc.schema-action=none

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
